### ISSUE TITLE
User control over winetricks WINEDEBUG=? / or no logging unless in debugmode?

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#18]
https://github.com/vitor251093/wineskin/blob/e3561af282a95f42251553107ba56407d56a4c2a/WineskinLauncher/WineskinLauncherAppDelegate.m#L2148

I currently replaced with the following
WineDebugLine:[self.portManager plistObjectForKey:@"WINEDEBUG="];

To have more control over what's gets shown for bugs when using winetricks, or would it be better to link it to debug mode and disable all logging unless debugmode? (I did try to figure it out but it never worked so I read from the plist instead)

**Comment by vitor251093** [comment]
Well, the logs present today for the winetricks are enough to identify errors, so we are better leaving only those (even because recently Macs come with SSDs only, and SSDs life-span decreases if you do lots of writing procedures in the disk in a short period of time; which is how the winetrick log file is written today).

**Comment by Gcenx** [comment]
That is true, I was only adding that so I could disable the logging when I did not need it since I did try to link winetricks winedebug= to be disabled when not in debug mode but it never worked.

**Comment by vitor251093** [comment]
Ah yes, that's a doable thing to be considered. We can enable/disable the Winetrick logs. I guess now I understand what you mean with winetrick debug mode in the other issue ;P

Indeed, we could make it "able to disabled". However, the problem here is that we never know for sure when a winetrick is going to succeed or fail. Also, some winetricks require files to be downloaded manually, and they say that in the logs. Disabling the logs, even in an optional manner, would lead many users to mistakes.

**Comment by Gcenx** [comment]
That's good ;P

I would still do it since 95% don't require manual downloads only edge items need manual downloading and those things that I noticed were never really needed to get my game/application working

If it was something like dotnet/vcrun /directX I would understand but I only remember needing to download a benchmarking tool manually.

**Comment by vitor251093** [comment]
An example of an important manual winetrick is msxml3. We even uploaded it to PortingKit.com in order to make a direct link of it instead of asking ours users to download it.

Also, newcomers wouldn't know that this even exist. They would just think it failed, or that the winetrick isn't working.

**Comment by Gcenx** [comment]
Really?
The current versions of Winetricks downloads that for me

Or do you mean it can't be installed silently?

**Comment by Gcenx** [comment]
dotnet35sp1 always seems to fail for me...

Anyway the easy way to avoid those issue would be if Silent mode is enabled show a warning screen when winetricks is opened.

"Silent mode is enabled some winetricks might fail without error"

If they click "ok" it stay's in silent mode, if they pick "disable" then silent mode gets disabled until its enabled again.

**Comment by Gcenx** [comment]
Closing due to the implementation I added as discussed in #17
