### ISSUE TITLE
Establish community fork?

### ISSUE THREAD

**Issue by chrisballinger** [vitor251093/wineskin#21]
Since it looks like upstream is no longer maintained, it would probably be helpful to formally establish a new fork. I invited both of you @vitor251093 and @Gcenx to a new [WineskinCommunity](https://github.com/WineskinCommunity) GitHub organization and created a new import of the upstream repo here containing both of your latest changes:  https://github.com/WineskinCommunity/Wineskin

I'd suggest adopting something like the [Moya community guidelines](https://github.com/Moya/contributors) to encourage outside collaboration. Basically the idea is to invite people the organization early and often, and just protect the master branch by always requiring code review from another member.

**Comment by vitor251093** [comment]
Hello @chrisballinger !

Yeah, doh123 said that she doesn't have enough spare time anymore to work in Wineskin. Me and PaulTheTall talked with her, and she should add a redirect to the Wineskin original domain soon, so we can consider the project here has the official continuity to Wineskin.

About the Moya community guidelines: haven't all of them yet, but I like the idea. Since doh123 was the only one maintaining Wineskin, the fact that she didn't had enough time made Wineskin stop. With a community, that shouldn't be a problem anymore.

Me and @Gcenx (specially @Gcenx lately xD) have been working in some fixes and improvements in Wineskin, and the issue are almost clean now. I think that we can clear those issues first (just the ones that are present by today, May 20th 2018), to solve those old problems, and then we can start been more organised and following the Moya guidelines to the letter. What do you think?

**Comment by chrisballinger** [comment]
Ya sounds good! I just bought and set up https://wineskin.app to point to a new static site here:  https://github.com/WineskinCommunity/wineskincommunity.github.io

I gave both of you admin access to the https://github.com/WineskinCommunity organization, so feel free to invite whoever else you think would be a good addition.
