### ISSUE TITLE
Build Error: Undeclared 'VMMVideoCardManager'

### ISSUE THREAD

**Issue by baalansellers** [vitor251093/wineskin#47]
Is VMMVideoCardManager one of the dependencies that Carthage should have setup for me first?

I'm getting two build errors for WineskinLauncher while following the README steps for building, both for the same line (WineskinApp and Wineskin Winery built fine):

```
use of undeclared identifier 'VMMVideoCardManager'; did you mean 'VMMVideoCardNameKey'?

    VMMVideoCard* vc = [VMMVideoCardManager bestInternalVideoCard];
                        ^~~~~~~~~~~~~~~~~~~
                        VMMVideoCardNameKey
```

and

```
no visible @interface for 'NSString' declares the selector 'bestInternalVideoCard'

    VMMVideoCard* vc = [VMMVideoCardManager bestInternalVideoCard];
```

https://github.com/vitor251093/wineskin/blob/3faf68dcb5d28d2e5cf73c2c8936bebb17eb0fec/WineskinLauncher/WineskinLauncherAppDelegate.m#L1085

**Comment by Gcenx** [comment]
I believe WineskinLauncher is not importing ObjectiveC_Extension that’s why the build would be failing, that’s also why the project is showing as “failing” within the Readme.

I think Vitor and myself didn’t really notice since we both build the project within XCode and make the required changes anyway.

If your building to just use this to replace the official Wineskin release I recommend instead going [here](https://github.com/Gcenx/WineskinServer) that’s a project build from EngineRepacking2 by myself with afew slight changes plus what ever I’m working on that gets committed back here once it’s stable.

**Comment by baalansellers** [comment]
Ah yes, that got it going. Thanks!
