### ISSUE TITLE
Use macdriver & overrider issue

### ISSUE THREAD

**Issue by Gcenx** [vitor251093/wineskin#8]
Once MAC driver is enabled "decorate windows" check box is disabled but still yet (not an issue)

Once overried is selected "decorate windows" check box is still disabled if you have macdriver enabled before using orerride option, to undo this need to exit screen settings or swap bad and enable and disable macdriver to enable "decorate windows" is usable again.

Also

Decorate Windows when using VirtualDesktop, even when checked manually is not respected now, loaded up a Virtual Desktop with it enabled and the application looks like a Windows Application

**Comment by vitor251093** [comment]
> Once overried is selected "decorate windows" check box is still disabled if you have macdriver enabled before using orerride option, to undo this need to exit screen settings or swap bad and enable and disable macdriver to enable "decorate windows" is usable again.

Fixed it ;)

> Decorate Windows when using VirtualDesktop, even when checked manually is not respected now, loaded up a Virtual Desktop with it enabled and the application looks like a Windows Application

That's correct. We may disabled it while using VirtualDesktop as well.

**Comment by Gcenx** [comment]
Closing as I made the change in the latest pull request, disabled completely when using Override option

**Comment by vitor251093** [comment]
> Closing as I made the change in the latest pull request, disabled completely when using Override option

The matter is not with Override, is with VirtualDesktop, specifically :P 

> Decorate Windows when using VirtualDesktop, even when checked manually is not respected now, loaded up a Virtual Desktop with it enabled and the application looks like a Windows Application

**Comment by vitor251093** [comment]
I will check that.

**Comment by vitor251093** [comment]
It should work properly now. Something that would be really helpful is a change in the Screen Options window, in order to separate in more proper groups and categories.

-> (X11 / Mac Driver) & (Auto-detect GPU) & (Direct3D Boost)
-> X11 -> (Automatic / Override) & (Color Depth) & (Switch Pause)
-> X11 -> Override -> (Virtual Desktop / Normal Windows) & (Decorate Windows) & (Installer Options)
-> X11 -> Override -> Virtual Desktop -> (Fullscreen / Windowed) & (Resolution)

That would be a division which is closer to reality, and which only show/enable options when they are functional in a specific order. It would even open space to add more Mac Driver options, like the Retina Mode.
